name: Markdown Spell Check

on:
  pull_request:
    paths:
      - '**/*.md'

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install markdown-spellcheck
        run: npm install -g markdown-spellcheck

      - name: Run spell check
        run: |
          # Run mdspell with non-interactive option
          mdspell "**/*.md" || exit 1

          # Check for errors and fail if any are found
          if [ $? -ne 0 ]; then
            echo "Spelling issues found. Fix them before proceeding."
            exit 1
          fi
